build:
	go build
	go install

uninstall:
	luno-stream-service -service uninstall

install:
	go install
	luno-stream-service -service install

stop:
	luno-stream-service -service stop

start:
	luno-stream-service -service start

clean:
	rm luno-stream-service
